document:
  name: Linee Guida Tecnologie e standard sicurezza API

  description:
      Linee Guida Tecnologie e standard per la sicurezza 
      dell'interoperabilità tramite API dei sistemi informatici
  tags:
    - sicurezza
    - interoperabilità
    - API
    - linee guida