document:
  name: Linee guida per accesso telematico ai servizi della Pubblica Amministrazione

  description:
      Linee guida per accesso telematico ai servizi della Pubblica Amministrazione

  tags:
    - accesso ai servizi
    - interoperabilità
    - API
    - linee guida